source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
# Note: Ruby 3.4.0+ removed kconv library which CocoaPods 1.15.2 requires.
# Use Ruby 3.3.x or earlier to avoid this issue.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
